colorscheme wombat
if has("mac")
  set guifont=Monaco:h13.00
  set fuopt=maxhorz,maxvert
else
  set gfn=Droid\ Sans\ Mono\ 11
end

set guioptions-=T  "remove toolbar
set guioptions-=m  "remove menu

set lines=47
set columns=161
