colorscheme wombat
if has("mac")
  set guifont=Inconsolata:h14.00
  set fuopt=maxhorz,maxvert
end

set guioptions-=T  "remove toolbar
set guioptions-=m  "remove menu
set guioptions-=r  "remove right scrollbar
set guioptions-=L  "remove left scrollbar

set lines=47
set columns=161
